Repository neo4j/apoc, pull requests merged in 2022-11, with the labels that each got.

#219 [4HrPR2Rm] Use internal function instead of procedure for compatibility check.
  core/src/main/java/apoc/cypher/CypherInitializer.java
  core/src/test/java/apoc/cypher/CypherIsVersionDifferentTest.java
  test-utils/src/main/java/apoc/periodic/PeriodicTestUtils.java
Labels: team-cypher-surface, 5.2

#232 [NOID] Fixes CVE-2022-42889 in transitive dependencies
  .github/workflows/CI.yaml
  common/build.gradle
  core/build.gradle
  core/src/main/java/apoc/export/csv/CsvEntityLoader.java
  teamcity-repository.gradle
  test-utils/src/main/java/apoc/periodic/PeriodicTestUtils.java
Labels: cherry-picked, 5.2

#229 [4Bmcyc2U] Fix and enable some ignored tests
  common/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
  common/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
  common/src/test/java/apoc/util/UtilIT.java
  core/src/main/java/apoc/export/cypher/ExportCypher.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  core/src/test/java/apoc/load/LoadJsonTest.java
Labels: dev

#235 [ahK775nK] Take into account minor versions for versions.json
  build.gradle
Labels: team-cypher-surface

#242 Fixes password length, bumps testContainer version
  build.gradle
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: bug, team-cypher-surface, 5.3

#243 [NOID] Removes load json test, the data is not in the external API anymore
  core/src/test/java/apoc/load/LoadJsonTest.java
Labels: bug, team-cypher-surface, 5.3

#238 [4Bmcyc2U] Try fixing flaky testDeadlockException
  core/src/test/java/apoc/refactor/rename/RenameTest.java
Labels: 5.3

#239 [4Bmcyc2U] Fix ignored testGeocodeGoogle
  core/src/test/java/apoc/spatial/GeocodeTest.java
Labels: 5.3

#249 [eRGoCYQI] Installs Snyk monitor GitHub action on PRs
  .github/workflows/CI.yaml
  common/build.gradle
  test-utils/build.gradle
Labels: team-cypher-surface, dev

#248 Update Docker env help
  readme.adoc
Labels: documentation, team-cypher-surface, 5.3

#251 [eRGoCYQI] Fixes all Snyk dependency issues of medium security level
  .github/workflows/CI.yaml
  common/build.gradle
  core/build.gradle
  core/src/test/java/apoc/load/XmlTest.java
  core/src/test/java/apoc/refactor/CloneSubgraphTest.java
  core/src/test/java/apoc/text/StringsTest.java
  core/src/test/java/apoc/trigger/TriggerDisabledTest.java
  test-utils/build.gradle
Labels: team-cypher-surface, dev

#253 [eRGoCYQI] Solves problem with empty GITHUB_REF for branches
  .github/workflows/CI.yaml
Labels: team-cypher-surface, dev

#247 [Zl3h9sM8] apoc.schema.relationships return wrong output for relationship indexes
  common/src/main/java/apoc/result/IndexConstraintNodeInfo.java
  common/src/main/java/apoc/result/IndexConstraintRelationshipInfo.java
  core/src/main/java/apoc/schema/Schemas.java
  core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
  core/src/test/java/apoc/schema/SchemasTest.java
Labels: dev

#252 Un-ignore working test
  core/src/test/java/apoc/meta/MetaEnterpriseFeaturesTest.java
  test-utils/build.gradle
Labels: team-cypher-surface, 5.3

#241 [4Bmcyc2U] Fix ignored S3 tests
  common/build.gradle
  common/src/test/java/apoc/util/s3/S3TestUtil.java
  core/src/test/java/apoc/export/ExportS3PerformanceTest.java
  core/src/test/java/apoc/export/csv/ExportCsvS3Test.java
  core/src/test/java/apoc/export/cypher/ExportCypherS3Test.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLS3Test.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTestUtil.java
  core/src/test/java/apoc/export/json/ExportJsonS3Test.java
  core/src/test/java/apoc/export/json/ExportJsonTest.java
  test-utils/build.gradle
  test-utils/src/main/java/apoc/util/FileTestUtil.java
  test-utils/src/main/java/apoc/util/s3/S3BaseTest.java
  test-utils/src/main/java/apoc/util/s3/S3Container.java
  test-utils/src/main/java/apoc/util/s3/S3ParamsExtractorTest.java
  test-utils/src/main/java/apoc/util/s3/S3TestUtil.java
Labels: 5.3
