Repository neo4j/apoc, pull requests merged in 2022-10, with the labels that each got.

#202 [hcaaOlXR] Various security fixes
  core/src/main/java/apoc/load/Xml.java
  core/src/test/java/apoc/load/XmlTest.java
Labels: bug, team-cypher-surface, 5.1

#186 [UHxIZ8JO] Add CodeQL
  .github/GH-ROBOTS.txt
  .github/workflows/CI.yaml
  common/src/main/java/apoc/export/util/ElementCounter.java
Labels: team-cypher-surface, 5.1

#205 [hcaaOlXR] Protect from Billion Laughs
  core/src/main/java/apoc/load/Xml.java
  core/src/test/java/apoc/load/XmlTest.java
  core/src/test/resources/xml/billion_laughs.xml
Labels: bug, team-cypher-surface, 5.1

#207 [9uFWHlVy] Check compatibility on system database instead of default database
  core/src/main/java/apoc/cypher/CypherInitializer.java
  core/src/test/java/apoc/cypher/CypherIsVersionDifferentTest.java
Labels: team-cypher-surface

#211 [NOID] Bump Neo4j to 5.2.0
  build.gradle
  readme.adoc
Labels: bug, team-cypher-surface

#212 [UHxIZ8JO] Grant CodeQL permissions
  .github/workflows/CI.yaml
Labels: bug, team-cypher-surface, 5.2

#216 Update testJaroWinklerDistance test expectation
  core/src/test/java/apoc/text/StringsTest.java
Labels: team-cypher-surface, 5.2

#217 [uGTIvlKp] Add link to extended and update readme matrix
  readme.adoc
Labels: documentation, team-cypher-surface, 5.2

#223 Iterate over apoc release tag names
  build.gradle
Labels: bug, team-cypher-surface, 5.2

#224 [NOID] 5.x fix apoc versions script 2
  build.gradle
Labels: bug, team-cypher-surface, 5.2
