Repository neo4j/apoc, pull requests merged in 2022-12, with the labels that each got.

#254 [vULR7sSU] Update APOC descriptions
  core/src/main/java/apoc/algo/PathFinding.java
  core/src/main/java/apoc/coll/Coll.java
  core/src/main/java/apoc/diff/Diff.java
  core/src/main/java/apoc/export/arrow/ExportArrow.java
  core/src/main/java/apoc/load/LoadArrow.java
  core/src/main/java/apoc/nodes/Grouping.java
  core/src/main/java/apoc/nodes/Nodes.java
  core/src/main/java/apoc/stats/DegreeDistribution.java
  core/src/main/java/apoc/text/Strings.java
  core/src/test/java/apoc/help/HelpTest.java
Labels: docs, 5.3

#258 Remove use of getID
  common/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
  common/src/main/java/apoc/result/VirtualNode.java
  common/src/main/java/apoc/result/VirtualRelationship.java
  common/src/main/java/apoc/result/WrappedNode.java
  common/src/main/java/apoc/util/Util.java
  common/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
  common/src/main/java/org/neo4j/cypher/export/DatabaseSubGraph.java
  common/src/test/java/apoc/result/VirtualNodeTest.java
  core/src/main/java/apoc/export/arrow/ExportResultStrategy.java
  core/src/main/java/apoc/export/csv/CsvEntityLoader.java
  core/src/main/java/apoc/export/csv/CsvFormat.java
  core/src/main/java/apoc/export/csv/ExportCSV.java
  core/src/main/java/apoc/export/csv/ImportCsv.java
  core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java
  core/src/main/java/apoc/meta/Meta.java
  core/src/main/java/apoc/neighbors/Neighbors.java
  core/src/main/java/apoc/path/PathExplorer.java
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/main/java/apoc/refactor/util/RefactorUtil.java
  core/src/main/java/apoc/spatial/Distance.java
  core/src/test/java/apoc/number/exact/ExactTest.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
Labels: team-cypher-surface

#240 [eOxJMLMv] Checks redirects for blocked IPs instead of just final location.
  common/src/main/java/apoc/ApocConfig.java
  common/src/main/java/apoc/util/FileUtils.java
  common/src/main/java/apoc/util/Util.java
  common/src/test/java/apoc/util/UtilIT.java
  core/src/main/java/apoc/load/Xml.java
  core/src/test/java/apoc/load/XmlTest.java
Labels: bug, team-cypher-surface, 5.3

#260 [NOID] Bump version to 5.4.0
  build.gradle
  readme.adoc
Labels: team-cypher-surface, dev

#246 [RwTvbEuL] Schema updates for new relationship constraints
  common/src/main/java/apoc/util/Util.java
  common/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
  core/src/main/java/apoc/index/SchemaIndex.java
  core/src/main/java/apoc/meta/Meta.java
  core/src/main/java/apoc/schema/SchemaConfig.java
  core/src/main/java/apoc/schema/Schemas.java
  core/src/test/java/apoc/index/SchemaIndexTest.java
  core/src/test/java/apoc/meta/MetaTest.java
  core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
  core/src/test/java/apoc/schema/SchemasTest.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: team-cypher-surface, 5.4

#244 [NwnPuJ91] Rewrite tests for failures in a safer way
  common/src/test/java/apoc/util/DateParseUtilTest.java
  common/src/test/java/apoc/util/UtilIT.java
  core/src/main/java/apoc/atomic/Atomic.java
  core/src/test/java/apoc/atomic/AtomicTest.java
  core/src/test/java/apoc/export/ExportStreamsStatementsTest.java
  core/src/test/java/apoc/export/csv/ExportCsvIT.java
  core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  core/src/test/java/apoc/hashing/FingerprintingTest.java
  core/src/test/java/apoc/load/LoadJsonTest.java
  core/src/test/java/apoc/load/XmlTest.java
  core/src/test/java/apoc/meta/CollEnterpriseTest.java
  core/src/test/java/apoc/path/PathsTest.java
  core/src/test/java/apoc/periodic/PeriodicTest.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
  core/src/test/java/apoc/spatial/GeocodeTest.java
  core/src/test/java/apoc/spatial/SpatialTest.java
  core/src/test/java/apoc/trigger/TriggerTest.java
  core/src/test/java/apoc/util/UtilTest.java
  core/src/test/java/apoc/util/UtilsTest.java
  core/src/test/java/apoc/warmup/WarmupEnterpriseTest.java
Labels: team-cypher-surface, dev

#265 [3KXXQazJ] Fix bug with serializing arrays of primitive values for json export query
  common/src/main/java/apoc/meta/Types.java
  core/src/main/java/apoc/export/json/JsonFormat.java
  core/src/test/java/apoc/export/json/ExportJsonTest.java
Labels: bug, team-cypher-surface, 5.4

#266 [i19tvtq1] Add Trello Traceability GHA to the CI
  .github/workflows/traceability.yml
  readme.adoc
Labels: team-cypher-surface, 5.4
