Repository neo4j/apoc, pull requests merged in 2022-09, with the labels that each got.

#171 Use DefaultDatabaseResolver to resolve default db (instead of Config)
  core/src/main/java/apoc/cypher/CypherInitializer.java
Labels: team-cypher-surface, 5.0

#172 Improve backtick sanitization
  common/src/main/java/apoc/util/Util.java
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/main/java/apoc/refactor/rename/Rename.java
  core/src/main/java/apoc/schema/Schemas.java
  core/src/test/java/apoc/util/UtilTest.java
Labels: team-cypher-surface, 5.0

#169 5.0 add storage engine check
  common/src/main/java/apoc/ApocConfig.java
  core/src/main/java/apoc/warmup/Warmup.java
  core/src/test/java/apoc/warmup/WarmupEnterpriseTest.java
  core/src/test/java/apoc/warmup/WarmupTest.java
  docs/asciidoc/modules/ROOT/pages/overview/apoc.warmup/apoc.warmup.run.adoc
Labels: team-cypher-surface, 5.0

#168 Remove the neo4jVersions gradle property
  build.gradle
Labels: team-cypher-surface, 5.0

#183 Fix "./gradlew versions" task
  build.gradle
Labels: team-cypher-surface

#182 Bumps version of neo4j
  build.gradle
  readme.adoc
Labels: team-cypher-surface, 5.0

#184 respect config.writeNodeProperties when writing node details (#3152)
  common/src/main/java/apoc/export/util/ExportConfig.java
  core/src/main/java/apoc/export/json/ExportJson.java
  core/src/main/java/apoc/export/json/JsonFormatSerializer.java
  core/src/test/java/apoc/export/json/ExportJsonS3Test.java
  core/src/test/java/apoc/export/json/ExportJsonTest.java
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/MapPath.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/all.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/all_array.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/all_fields.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/all_id_as_keys.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/data.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/graph.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/listPath.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/listRel.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/query_nodes_path.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/with_node_properties.json
  docs/asciidoc/modules/ROOT/examples/data/exportJSON/without_node_properties.json
  docs/asciidoc/modules/ROOT/pages/export/json.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.json.all.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.json.data.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.json.graph.adoc
  docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.json.query.adoc
Labels: bug, 5.1, cherry-picked

#185 Remove references to '-rc' releases
  build.gradle
  docs/asciidoc/antora.yml
  docs/build.gradle
  readme.adoc
Labels: team-cypher-surface, 5.1

#194 Fixing a test after making 'text-2' the deafult text index provider.
  core/src/test/java/apoc/schema/SchemasTest.java
Labels: team-cypher-surface, 5.1

#199 Invalid unicode character with apoc.import.graphml (#3107)
  common/src/main/java/apoc/export/util/FormatUtils.java
  core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java
  core/src/main/java/apoc/export/graphml/XmlGraphMLWriter.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  core/src/test/resources/fileWithUnicode.graphml
Labels: 5.1, cherry-picked

#189 [bcIQ3oqd] Remove deprecated apoc.convert functions
  common/src/main/java/apoc/util/Util.java
  core/src/main/java/apoc/convert/Convert.java
  core/src/test/java/apoc/ApocSplitTest.java
  core/src/test/java/apoc/convert/ConvertTest.java
Labels: team-cypher-surface, 5.1

#191 Fixes #2739: Allow apoc.spatial.geoCodeOnce to also receive config via procedure call (#2832)
  common/src/test/resources/spatial.json
  core/src/main/java/apoc/spatial/Geocode.java
  core/src/test/java/apoc/spatial/GeocodeTest.java
  core/src/test/java/apoc/spatial/SpatialTest.java
Labels: cherry-picked

#195 Fixes neo4j-contrib/neo4j-apoc-procedures#2931: The apoc.import.csv procedure doesn't batch correctly
  core/src/main/java/apoc/export/csv/CsvEntityLoader.java
  core/src/main/java/apoc/export/csv/CsvLoaderConfig.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
  core/src/test/resources/csv-inputs/.gitignore
  core/src/test/resources/csv-inputs/largeFile.csv
Labels: cherry-picked

#201 `apoc.meta.relTypeProperties` doest not return relationship information (#2935)
  core/src/main/java/apoc/cypher/CypherInitializer.java
  core/src/main/java/apoc/meta/Meta.java
  core/src/test/java/apoc/meta/MetaTest.java
Labels: cherry-picked

#203 [NOID] Fix broken tests so that CI can pass
  core/src/test/java/apoc/load/LoadJsonTest.java
  core/src/test/java/apoc/load/XmlTest.java
Labels: bug, team-cypher-surface, 5.1
