Repository neo4j/apoc, pull requests merged in 2023-10, with the labels that each got.

#499 [Gc8EZpDO] Clean up some usages of getId() which is deprecated
  common/src/main/java/apoc/get/Get.java
  common/src/main/java/apoc/util/Util.java
  core/src/main/java/apoc/algo/Cover.java
  core/src/main/java/apoc/coll/Coll.java
  core/src/main/java/apoc/create/Create.java
  core/src/main/java/apoc/nodes/Nodes.java
  core/src/main/java/apoc/path/PathExplorer.java
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/test/java/apoc/algo/CoverTest.java
  core/src/test/java/apoc/create/CreateTest.java
  core/src/test/java/apoc/nodes/NodesTest.java
  core/src/test/java/apoc/path/ExpandPathTest.java
  core/src/test/java/apoc/path/SequenceTest.java
  core/src/test/java/apoc/path/SubgraphTest.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
Labels: team-cypher-surface, dev

#506 [pLz5YbCW] update versions
  LICENSES.txt
  NOTICE.txt
  build.gradle
  readme.adoc
Labels: dev

#501 [NoID] update dependencies according to neo4j bumps
  LICENSES.txt
  NOTICE.txt
  common/build.gradle
  core/build.gradle
Labels: dev

#515 [NOID] Remove explicit netty dependency
  LICENSES.txt
  NOTICE.txt
  core/build.gradle
  core/src/main/java/io/netty/buffer/PooledByteBufAllocatorL.java
  licenses-source-header.gradle
Labels: cherry-picked, dev

#488 [NOID] Update param name to delay
  core/src/main/java/apoc/periodic/Periodic.java
Labels: team-cypher-surface, dev

#518 [NOID] Update the docker command to match the one in docs
  readme.adoc
Labels: team-cypher-surface, dev

#517 [q3KTZ83O] Remove strange clean up method
  core/src/main/java/apoc/export/csv/CsvFormat.java
  core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java
Labels: team-cypher-surface, dev
