Repository neo4j/apoc, pull requests merged in 2023-07, with the labels that each got.

#448 [NOID] Clean up some usages of the deprecated id() and reduce warnings
  common/src/test/java/apoc/result/VirtualNodeTest.java
  core/src/main/java/apoc/label/Label.java
  core/src/main/java/apoc/nodes/Nodes.java
  core/src/test/java/apoc/graph/GraphsTest.java
Labels: team-cypher-surface, dev

#451 [VpC8nqNz] Adds license and notice validation to the CI
  .github/workflows/CI.yaml
Labels: team-cypher-surface

#454 [lQ6QYETL] Bump version to 5.11.0
  LICENSES.txt
  NOTICE.txt
  build.gradle
  readme.adoc
Labels: team-cypher-surface, dev

#453 [ZIv6F2QY] Allow Command Expansion APOC
  common/src/main/java/apoc/ApocConfig.java
  common/src/test/java/apoc/ApocConfigTest.java
Labels: team-cypher-surface, dev

#455 [LePmOHly] Fix flakey index test
  core/src/test/java/apoc/schema/SchemasTest.java
Labels: team-cypher-surface, dev

#457 [NOID] Remove overrideImplementation argument
  core/src/test/java/apoc/export/BigGraphTest.java
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
  test-utils/src/main/java/apoc/util/TestUtil.java
Labels: dev

#462 [NOID] Fix licenses
  LICENSES.txt
  NOTICE.txt
Labels: team-cypher-surface, dev

#460 [7BVOtcmX] Add debug statement to see if we can figure out cause of flaky test
  test-utils/src/main/java/apoc/cypher/CypherTestUtil.java
Labels: team-cypher-surface, dev

#461 [NOID] Some warning and deprecation clean up 🧹
  core/src/main/java/apoc/coll/Coll.java
  core/src/test/java/apoc/atomic/AtomicTest.java
  core/src/test/java/apoc/cypher/CypherTest.java
  core/src/test/java/apoc/export/BigGraphTest.java
  core/src/test/java/apoc/export/ImportAndLoadCoreSecurityTest.java
  core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
  core/src/test/java/apoc/meta/MetaTest.java
  core/src/test/java/apoc/refactor/CloneSubgraphTest.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
  it/src/test/java/apoc/it/core/ExportCsvS3Test.java
  it/src/test/java/apoc/it/core/ExportCypherEnterpriseFeaturesTest.java
  it/src/test/java/apoc/it/core/ExportGraphMLS3Test.java
  it/src/test/java/apoc/it/core/ExportJsonS3Test.java
  it/src/test/java/apoc/it/core/ImportJsonEnterpriseFeaturesTest.java
Labels: team-cypher-surface, dev
