Repository neo4j/apoc, pull requests merged in 2023-09, with the labels that each got.

#487 [NOID] Bump arrow versions
  LICENSES.txt
  NOTICE.txt
  core/build.gradle
  test-utils/build.gradle
Labels: team-cypher-surface, dev

#485 [W9VglL9c] Bump APOC and Neo versions to 5.13
  LICENSES.txt
  NOTICE.txt
  build.gradle
  core/build.gradle
  readme.adoc
Labels: team-cypher-surface, dev

#491 [NOID] temporarily reduce startup attempts
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: dev

#492 [47wOlqLp] Adds option to customize decompression ratio
  common/src/main/java/apoc/ApocConfig.java
  common/src/main/java/apoc/export/util/LimitedSizeInputStream.java
  common/src/test/java/apoc/ApocConfigCommandExpansionTest.java
  it/src/test/java/apoc/it/core/LoadCoreEnterpriseTest.java
Labels: team-cypher-surface, cherry-picked, dev

#494 Take into account minor versions that are larger than 9
  build.gradle
Labels: team-cypher-surface

#493 [NOID] Cleans up resources after the tests
  core/src/test/java/apoc/export/BigGraphTest.java
  core/src/test/java/apoc/export/ExportCoreSecurityTest.java
  core/src/test/java/apoc/export/ImportAndLoadCoreSecurityTest.java
  core/src/test/java/apoc/export/arrow/ArrowTest.java
  core/src/test/java/apoc/export/arrow/ExportArrowSecurityTest.java
  core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
  core/src/test/java/apoc/export/csv/ImportCsvLdbcTest.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherMultiRelTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  core/src/test/java/apoc/export/json/ExportJsonTest.java
  core/src/test/java/apoc/export/json/ImportJsonTest.java
  core/src/test/java/apoc/graph/GraphsTest.java
  core/src/test/java/apoc/hashing/FingerprintingTest.java
  core/src/test/java/apoc/help/HelpTest.java
  core/src/test/java/apoc/index/SchemaIndexTest.java
  core/src/test/java/apoc/label/LabelTest.java
  core/src/test/java/apoc/load/LoadJsonTest.java
  core/src/test/java/apoc/load/XmlTest.java
  core/src/test/java/apoc/load/relative/LoadRelativePathTest.java
  core/src/test/java/apoc/lock/LockTest.java
  core/src/test/java/apoc/log/Neo4jLogStreamTest.java
  core/src/test/java/apoc/map/MapsTest.java
  core/src/test/java/apoc/math/MathsTest.java
  core/src/test/java/apoc/math/RegressionTest.java
  core/src/test/java/apoc/merge/MergeTest.java
  core/src/test/java/apoc/meta/MetaTest.java
  core/src/test/java/apoc/neighbors/NeighborsTest.java
  core/src/test/java/apoc/nodes/GroupingTest.java
  core/src/test/java/apoc/nodes/NodesTest.java
  core/src/test/java/apoc/number/ArabicRomanTest.java
  core/src/test/java/apoc/number/NumbersTest.java
  core/src/test/java/apoc/number/exact/ExactTest.java
  core/src/test/java/apoc/path/ExpandPathTest.java
  core/src/test/java/apoc/path/LabelSequenceTest.java
  core/src/test/java/apoc/path/NodeFilterTest.java
  core/src/test/java/apoc/path/PathsTest.java
  core/src/test/java/apoc/path/RelSequenceTest.java
  core/src/test/java/apoc/path/SequenceTest.java
  core/src/test/java/apoc/path/SubgraphTest.java
  core/src/test/java/apoc/periodic/PeriodicTest.java
  core/src/test/java/apoc/refactor/util/PropertiesManagerTest.java
  it/src/test/java/apoc/it/core/ApocSplitTest.java
  it/src/test/java/apoc/it/core/ExportCsvIT.java
  it/src/test/java/apoc/it/core/ExportCsvS3Test.java
  it/src/test/java/apoc/it/core/ExportCypherS3Test.java
  it/src/test/java/apoc/it/core/ExportGraphMLS3Test.java
  it/src/test/java/apoc/it/core/ExportJsonS3Test.java
  it/src/test/java/apoc/it/core/StartupTest.java
Labels: team-cypher-surface, cherry-picked

#497 [NOID] Fix licenses after Neo update
  LICENSES.txt
  NOTICE.txt
Labels: team-cypher-surface, dev

#498 [3X06NMak] Update Scan to PartitionedScan as Scan is deprecated
  common/src/main/java/apoc/util/kernel/MultiThreadedGlobalGraphOperations.java
Labels: team-cypher-surface, dev

#496 [6zK6lL5F] Update to use new descriptions for new Cypher Types
  core/src/main/java/apoc/agg/Graph.java
  core/src/main/java/apoc/agg/MaxAndMinItems.java
  core/src/main/java/apoc/agg/Median.java
  core/src/main/java/apoc/agg/Product.java
  core/src/main/java/apoc/agg/Statistics.java
  core/src/main/java/apoc/algo/Cover.java
  core/src/main/java/apoc/algo/PathFinding.java
  core/src/main/java/apoc/atomic/Atomic.java
  core/src/main/java/apoc/coll/Coll.java
  core/src/main/java/apoc/convert/Convert.java
  core/src/main/java/apoc/convert/Json.java
  core/src/main/java/apoc/create/Create.java
  core/src/main/java/apoc/cypher/Cypher.java
  core/src/main/java/apoc/cypher/CypherFunctions.java
  core/src/main/java/apoc/data/url/ExtractURL.java
  core/src/main/java/apoc/date/Date.java
  core/src/main/java/apoc/diff/Diff.java
  core/src/main/java/apoc/export/csv/ExportCSV.java
  core/src/main/java/apoc/export/csv/ImportCsv.java
  core/src/main/java/apoc/export/cypher/ExportCypher.java
  core/src/main/java/apoc/export/graphml/ExportGraphML.java
  core/src/main/java/apoc/export/json/ExportJson.java
  core/src/main/java/apoc/graph/Graphs.java
  core/src/main/java/apoc/hashing/Fingerprinting.java
  core/src/main/java/apoc/help/Help.java
  core/src/main/java/apoc/index/SchemaIndex.java
  core/src/main/java/apoc/load/LoadArrow.java
  core/src/main/java/apoc/load/LoadJson.java
  core/src/main/java/apoc/load/Xml.java
  core/src/main/java/apoc/lock/Lock.java
  core/src/main/java/apoc/map/Maps.java
  core/src/main/java/apoc/merge/Merge.java
  core/src/main/java/apoc/meta/Meta.java
  core/src/main/java/apoc/neighbors/Neighbors.java
  core/src/main/java/apoc/nodes/Grouping.java
  core/src/main/java/apoc/nodes/Nodes.java
  core/src/main/java/apoc/number/Numbers.java
  core/src/main/java/apoc/number/exact/Exact.java
  core/src/main/java/apoc/path/PathExplorer.java
  core/src/main/java/apoc/path/Paths.java
  core/src/main/java/apoc/periodic/Periodic.java
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/main/java/apoc/refactor/rename/Rename.java
  core/src/main/java/apoc/schema/Schemas.java
  core/src/main/java/apoc/scoring/Scoring.java
  core/src/main/java/apoc/search/ParallelNodeSearch.java
  core/src/main/java/apoc/spatial/Distance.java
  core/src/main/java/apoc/stats/DegreeDistribution.java
  core/src/main/java/apoc/temporal/TemporalProcedures.java
  core/src/main/java/apoc/text/Phonetic.java
  core/src/main/java/apoc/text/Strings.java
  core/src/main/java/apoc/util/Utils.java
  core/src/main/java/apoc/warmup/Warmup.java
  core/src/test/java/apoc/help/HelpTest.java
Labels: team-cypher-surface, dev
