Repository neo4j/apoc, pull requests merged in 2023-01, with the labels that each got.

#270 [FmCGhDLD] Remove relationship constraint feature flag
  core/src/test/java/apoc/meta/MetaTest.java
  core/src/test/java/apoc/schema/SchemasTest.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: team-cypher-surface, 5.4

#272 [RhUZ6yD8] Renaming for allowlist and denylist
  common/src/main/java/apoc/meta/MetaConfig.java
  common/src/main/java/apoc/meta/Tables4LabelsProfile.java
  core/src/main/java/apoc/load/SkipWhitespaceInputStream.java
  core/src/main/java/apoc/path/LabelMatcherGroup.java
  core/src/main/java/apoc/path/LabelSequenceEvaluator.java
  core/src/main/java/apoc/path/NodeEvaluators.java
  core/src/main/java/apoc/path/PathExplorer.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTestUtil.java
  core/src/test/java/apoc/path/ExpandPathTest.java
  core/src/test/java/apoc/path/LabelSequenceTest.java
  core/src/test/java/apoc/path/NodeFilterTest.java
  core/src/test/java/apoc/path/SubgraphTest.java
  core/src/test/java/apoc/refactor/CloneSubgraphTest.java
Labels: team-cypher-surface, 5.4

#276 [zsiiACOA] Update the apoc.coll.different description to accurately describe the function
  core/src/main/java/apoc/coll/Coll.java
Labels: team-cypher-surface, docs, dev

#250 [gRNAet7B] Fixes trigger procedures in clusters for neo4j 5.x
  common/src/main/java/apoc/ApocConfig.java
  core/src/main/java/apoc/trigger/Trigger.java
  core/src/main/java/apoc/trigger/TriggerHandler.java
  core/src/main/java/apoc/trigger/TriggerHandlerNewProcedures.java
  core/src/main/java/apoc/trigger/TriggerInfo.java
  core/src/main/java/apoc/trigger/TriggerMetadata.java
  core/src/main/java/apoc/trigger/TriggerNewProcedures.java
  core/src/test/java/apoc/trigger/TriggerClusterRoutingTest.java
  core/src/test/java/apoc/trigger/TriggerEnterpriseFeaturesTest.java
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
  core/src/test/java/apoc/trigger/TriggerRestartTest.java
  core/src/test/java/apoc/trigger/TriggerTest.java
  test-utils/src/main/java/apoc/trigger/TriggerTestUtil.java
  test-utils/src/main/java/apoc/util/TestUtil.java
  test-utils/src/main/java/apoc/util/TestcontainersCausalCluster.java
Labels: dev

#274 [MiVboeTJ] Fixes slf4j apoc logger
  common/build.gradle
  test-startup/src/test/java/StartupTest.java
  test-utils/build.gradle
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: team-cypher-surface

#275 [8JV7MoEx] Remove EOL versions from APOC readme and fix broken image links
  images/apoc.gif
  images/apoc.png
  readme.adoc
Labels: team-cypher-surface, docs, dev

#282 [NOID] Revert "Remove relationship constraint feature flag"
  core/src/test/java/apoc/meta/MetaTest.java
  core/src/test/java/apoc/schema/SchemasTest.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: team-cypher-surface, dev

#281 [UDzPn3dS] Update readme about loading and unrestricting
  readme.adoc
Labels: team-cypher-surface, docs, dev

#287 [126ZorO2] Document that apoc.util.sha1 and apoc.text.random are not suitable for cryptographic use.
  core/src/main/java/apoc/text/Strings.java
  core/src/main/java/apoc/util/Utils.java
Labels: documentation, team-cypher-surface, dev

#261 [wokdlhX3] Extract code from APOC core which is only used in APOC extended
  common/src/main/antlr/apoc/custom/Signature.g4
  common/src/main/java/apoc/ApocConfig.java
  common/src/main/java/apoc/ApocExtensionFactory.java
  common/src/main/java/apoc/Description.java
  common/src/main/java/apoc/RegisterComponentFactory.java
  common/src/main/java/apoc/SystemLabels.java
  common/src/main/java/apoc/SystemPropertyKeys.java
  common/src/main/java/apoc/export/cypher/FileManagerFactory.java
  common/src/main/java/apoc/load/LoadJsonUtils.java
  common/src/main/java/apoc/load/Mapping.java
  common/src/main/java/apoc/load/util/JdbcUtil.java
  common/src/main/java/apoc/load/util/LoadCsvConfig.java
  common/src/main/java/apoc/load/util/LoadJdbcConfig.java
  common/src/main/java/apoc/result/BooleanResult.java
  common/src/main/java/apoc/result/IdsResult.java
  common/src/main/java/apoc/result/KernelInfoResult.java
  common/src/main/java/apoc/result/KeyValueResult.java
  common/src/main/java/apoc/result/NodeValueErrorMapResult.java
  common/src/main/java/apoc/result/NodeWithMapResult.java
  common/src/main/java/apoc/result/StoreInfoResult.java
  common/src/main/java/apoc/result/StringResult.java
  common/src/main/java/apoc/result/TransactionInfoResult.java
  common/src/main/java/apoc/result/VirtualNode.java
  common/src/main/java/apoc/result/VirtualPath.java
  common/src/main/java/apoc/result/VirtualRelationship.java
  common/src/main/java/apoc/util/FileUtils.java
  common/src/main/java/apoc/util/JsonUtil.java
  common/src/main/java/apoc/util/UrlResolver.java
  common/src/main/java/apoc/util/Util.java
  common/src/main/java/apoc/uuid/UuidConfig.java
  log.txt
  test-utils/src/main/java/apoc/util/GoogleCloudStorageContainerExtension.java
  test-utils/src/main/java/apoc/util/MySQLContainerExtension.java
  test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
  test-utils/src/main/java/apoc/util/TestUtil.java
  test-utils/src/main/java/org/neo4j/test/rule/DbmsRule.java
Labels: team-cypher-surface, 5.4

#285 [480BDuYi] Try de-flake some trigger tests with embedded db
  test-utils/src/main/java/apoc/trigger/TriggerTestUtil.java
Labels: 5.4

#283 [gRNAet7B] Changed AtomicReference with 1-elem array
  core/src/main/java/apoc/trigger/TriggerHandlerNewProcedures.java
Labels: cherry-picked, 5.4

#289 [yHvDctRN] Add tests and docs about $transactionId
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
Labels: dev

#295 Revert 273 5.x begin transaction
  test-utils/src/main/java/org/neo4j/test/rule/DbmsRule.java
Labels: team-cypher-surface, 5.4

#192 [NOID] Fix docs cve 2021-27568 (neo4j-contrib/neo4j-apoc-procedures#2953)
  common/build.gradle
Labels: cherry-picked

#221 [NOID] Added var. adoc and test for meta configs (neo4j-contrib/neo4j-apoc-procedures#3032)
  core/src/test/java/apoc/meta/MetaTest.java
  core/src/test/java/apoc/nodes/GroupingTest.java
Labels: cherry-picked, dev

#220 [NOID] Fixes neo4j-contrib/neo4j-apoc-procedures#3070: The apoc.export.csv.all with bulkImport config doesn't work with a file name without extension
  common/src/main/java/apoc/export/cypher/FileManagerFactory.java
  core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
Labels: cherry-picked, dev

#301 [NOID] Remove log file which was committed by mistake
  log.txt
Labels: team-cypher-surface, dev

#288 [gcL5e77c] Fix edge cases in trigger methods
  core/src/main/java/apoc/trigger/TriggerHandlerNewProcedures.java
  core/src/main/java/apoc/trigger/TriggerNewProcedures.java
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
Labels: dev

#206 [NOID] Fixes neo4j-contrib/neo4j-apoc-procedures#2992: apoc.diff.nodes() returns list-type properties as different when they are the same
  core/src/main/java/apoc/diff/Diff.java
  core/src/test/java/apoc/diff/DiffTest.java
Labels: cherry-picked

#309 [NOID] Update version matrix
  readme.adoc
Labels: team-cypher-surface, docs
