Repository neo4j/apoc, pull requests merged in 2023-12, with the labels that each got.

#549 [brxa3W4m] Adapt to Neo4j dependency bump
  LICENSES.txt
  NOTICE.txt
  common/build.gradle
Labels: team-cypher-surface, dev

#551 [NOID] Updates neo4j and apoc version
  build.gradle
  readme.adoc
Labels: team-cypher-surface

#552 [NOID] Solves bug where bot cannot update the format / license comment
  .github/actions/gradle-command-on-pr/action.yaml
Labels: team-cypher-surface

#542 [G9u7OAg9] Ignore check for optimizations if the format is CSV
  common/src/main/java/apoc/export/util/ExportConfig.java
  common/src/main/java/apoc/export/util/ExportFormat.java
  core/src/main/java/apoc/export/csv/ExportCSV.java
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
Labels: team-cypher-surface, dev

#557 [pgcq5tlP] Fix flaky test
  it/src/test/java/apoc/it/core/TriggerEnterpriseFeaturesTest.java
Labels: dev

#556 [c11DvQNF] Investigate flaky test
  common/src/main/java/apoc/export/util/ExportConfig.java
  common/src/main/java/apoc/export/util/ExportFormat.java
  core/src/main/java/apoc/cypher/CypherInitializer.java
  core/src/main/java/apoc/export/csv/ExportCSV.java
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
  it/src/test/java/apoc/it/core/StartupTest.java
  test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: dev
