Repository neo4j/apoc, pull requests merged in 2023-11, with the labels that each got.

#520 [NOID] Adds job to apply formatting in PRs
  .github/actions/gradle-command-on-pr/action.yaml
  .github/workflows/ChatOps.yml
  .github/workflows/spotlessApply-command.yml
Labels: enhancement

#525 [NOID] Updates gradle version
  build.gradle
  common/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: cherry-picked

#519 [jMd3ZuqI] Fix arrow flaky tests
  core/src/main/java/apoc/export/arrow/ExportArrowFileStrategy.java
  core/src/main/java/apoc/export/arrow/ExportArrowStreamStrategy.java
Labels: bug, dev

#513 [5kItK998] Fix bug in triggers
  core/src/main/java/apoc/trigger/Trigger.java
  core/src/main/java/apoc/trigger/TriggerHandler.java
  core/src/main/java/apoc/trigger/TriggerInfo.java
  core/src/test/java/apoc/trigger/TriggerTest.java
  it/src/test/java/apoc/it/core/TriggerEnterpriseFeaturesTest.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: bug

#529 [jyX5Zi3L] Fix bug in apoc.search.nodeAll and apoc.search.node
  core/src/main/java/apoc/search/ParallelNodeSearch.java
Labels: dev

#526 [Bc2lkk3N] Fix flaky test
  core/src/test/java/apoc/cypher/CypherTest.java
  test-utils/src/main/java/apoc/util/TransactionTestUtil.java
Labels: dev

#528 [54NHcNqK] Fix flaky test
  it/src/test/java/apoc/it/core/TriggerClusterRoutingTest.java
Labels: dev

#532 [NOID] Setups testing for JDK 21
  .github/actions/setup-jdk/action.yaml
  .github/actions/test-gradle-project/action.yaml
  .github/workflows/CI.yaml
Labels: team-cypher-surface

#527 [h99LDu82] Fix flaky test
  core/src/test/java/apoc/cypher/CypherTest.java
Labels: dev

#538 [gtjPFvMD] Fix coll support for lists coming from Nodes or Rels.
  LICENSES.txt
  NOTICE.txt
  common/src/main/java/apoc/convert/ConvertUtils.java
  core/src/main/java/apoc/coll/Coll.java
  core/src/test/java/apoc/coll/CollTest.java
Labels: team-cypher-surface, dev

#537 [NOID] Use Injected UrlAccessChecker for checking access to URLs
  common/src/main/java/apoc/ApocConfig.java
  common/src/main/java/apoc/load/LoadJsonUtils.java
  common/src/main/java/apoc/util/FileUtils.java
  common/src/main/java/apoc/util/JsonUtil.java
  common/src/main/java/apoc/util/Util.java
  core/src/main/java/apoc/export/csv/CsvEntityLoader.java
  core/src/main/java/apoc/export/csv/ImportCsv.java
  core/src/main/java/apoc/export/graphml/ExportGraphML.java
  core/src/main/java/apoc/export/json/ImportJson.java
  core/src/main/java/apoc/load/LoadArrow.java
  core/src/main/java/apoc/load/LoadJson.java
  core/src/main/java/apoc/load/Xml.java
Labels: NOT READY FOR MERGE, dev
