Repository neo4j/apoc, pull requests merged in 2023-04, with the labels that each got.

#347 [TOQo1n9M] Core part - apoc-hadoop dependency is conflicting 5.x (neo4j-contrib/neo4j-apoc-procedures#3450)
  processor/src/main/java/apoc/processor/ExtensionClassWriter.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: cherry-picked

#363 [ST3nW88b] Upgrade commons-configuration2 to 2.9.0.
  common/build.gradle
Labels: team-cypher-surface, dev

#349 [3QAbWQds] apoc.export.arrow.all ignores export file config
  common/src/main/java/apoc/ApocConfig.java
  core/src/main/java/apoc/export/arrow/ExportArrowService.java
  core/src/test/java/apoc/export/ExportCoreSecurityTest.java
  core/src/test/java/apoc/export/arrow/ArrowTest.java
  core/src/test/java/apoc/export/arrow/ExportArrowSecurityTest.java
Labels: dev

#364 [wr4kMP3r] ArithmeticException calling apoc.schema.nodes
  core/src/main/java/apoc/schema/Schemas.java
  core/src/test/java/apoc/schema/SchemasTest.java
Labels: dev

#367 [NOID] Bump version to 5.8.0
  build.gradle
  readme.adoc
Labels: team-cypher-surface, dev

#350 [f46vahOr] Fix Cypher export of constraints
  common/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
  common/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java
  common/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java
  common/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java
  common/src/main/java/apoc/export/util/NodesAndRelsSubGraph.java
  common/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
  common/src/main/java/org/neo4j/cypher/export/DatabaseSubGraph.java
  common/src/main/java/org/neo4j/cypher/export/SubGraph.java
  common/src/test/resources/init_neo4j_export_csv.cypher
  core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherTestUtils.java
  it/src/test/java/apoc/it/core/ExportCypherEnterpriseFeaturesTest.java
  it/src/test/java/apoc/it/core/ExportCypherS3Test.java
Labels: bug, team-cypher-surface, dev

#372 [NOID] Fix flaky geocode server errors (neo4j-contrib/neo4j-apoc-procedures#3527)
  core/src/test/java/apoc/spatial/GeocodeTest.java
Labels: cherry-picked
