Repository neo4j/apoc, pull requests merged in 2023-02, with the labels that each got.

#308 [4cnpX39y] Bump mockserver-netty version and org.apache.arrow version
  core/build.gradle
  test-utils/build.gradle
Labels: team-cypher-surface, dev

#313 [HQABUD5U] Improve coverNodes speed
  core/src/main/java/apoc/algo/Cover.java
Labels: team-cypher-surface, dev

#197 [NOID] Fixes #2826: The apoc.import.csv/graphml procedures create empty wrong empty nodes with UNIQUE constraint violation (#3006)
  common/src/main/java/apoc/export/util/BatchTransaction.java
  core/src/main/java/apoc/export/csv/CsvEntityLoader.java
  core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
Labels: cherry-picked

#306 [04b6IYYB] improve performance of apoc.meta procedures
  common/src/main/java/apoc/meta/MetaConfig.java
  common/src/main/java/apoc/meta/SampleMetaConfig.java
  common/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
  core/src/main/java/apoc/meta/Meta.java
  core/src/test/java/apoc/meta/MetaTest.java
Labels: team-cypher-surface, dev

#314 [NOID] Fix readme docs link
  readme.adoc
Labels: documentation, team-cypher-surface, dev

#310 [AJmycukR] Fix for apoc.import.graphml
  core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
Labels: team-cypher-surface, dev

#316 [NOID] Bump versions to 5.6.0
  build.gradle
  readme.adoc
Labels: team-cypher-surface, dev

#321 [NOID] Cleans up resources after the tests
  common/src/test/java/apoc/export/util/FormatUtilsTest.java
  common/src/test/java/apoc/result/VirtualNodeTest.java
  common/src/test/java/apoc/util/UtilQuoteTest.java
  common/src/test/java/apoc/util/kernel/MultiThreadedGlobalGraphOperationsTest.java
  core/src/test/java/apoc/ApocSplitTest.java
  core/src/test/java/apoc/agg/CollAggregationTest.java
  core/src/test/java/apoc/agg/GraphAggregationTest.java
  core/src/test/java/apoc/agg/MedianTest.java
  core/src/test/java/apoc/agg/PercentilesTest.java
  core/src/test/java/apoc/agg/ProductAggregationTest.java
  core/src/test/java/apoc/agg/StatisticsTest.java
  core/src/test/java/apoc/algo/CoverTest.java
  core/src/test/java/apoc/algo/PathFindingTest.java
  core/src/test/java/apoc/atomic/AtomicTest.java
  core/src/test/java/apoc/bitwise/BitwiseOperationsTest.java
  core/src/test/java/apoc/coll/ArrayListTest.java
  core/src/test/java/apoc/coll/CollTest.java
  core/src/test/java/apoc/coll/EqualityTest.java
  core/src/test/java/apoc/convert/ConvertJsonTest.java
  core/src/test/java/apoc/convert/ConvertTest.java
  core/src/test/java/apoc/create/CreateTest.java
  core/src/test/java/apoc/cypher/CypherInitializerTest.java
  core/src/test/java/apoc/cypher/CypherTest.java
  core/src/test/java/apoc/data/url/ExtractURLTest.java
  core/src/test/java/apoc/date/DateTest.java
  core/src/test/java/apoc/diff/DiffTest.java
  core/src/test/java/apoc/example/ExamplesTest.java
  core/src/test/java/apoc/refactor/CloneSubgraphTest.java
  core/src/test/java/apoc/refactor/rename/RenameTest.java
  core/src/test/java/apoc/schema/SchemasTest.java
  core/src/test/java/apoc/scoring/ScoringTest.java
  core/src/test/java/apoc/search/ParallelNodeSearchTest.java
  core/src/test/java/apoc/spatial/DistanceTest.java
  core/src/test/java/apoc/spatial/GeocodeTest.java
  core/src/test/java/apoc/spatial/SpatialTest.java
  core/src/test/java/apoc/stats/DegreeDistributionTest.java
  core/src/test/java/apoc/temporal/TemporalProceduresTest.java
  core/src/test/java/apoc/text/PhoneticTest.java
  core/src/test/java/apoc/text/StringCleanTest.java
  core/src/test/java/apoc/text/StringsTest.java
  core/src/test/java/apoc/trigger/TriggerDisabledTest.java
  core/src/test/java/apoc/trigger/TriggerTest.java
  core/src/test/java/apoc/util/UtilTest.java
  core/src/test/java/apoc/util/UtilsTest.java
  core/src/test/java/apoc/warmup/WarmupTest.java
  test-startup/src/test/java/StartupTest.java
Labels: team-cypher-surface, dev

#293 [NOID] Updates broken links
  common/src/main/java/apoc/util/FileUtils.java
Labels: team-cypher-surface

#315 [mIPA5H7K] Avoids double DNS lookup in the load methods
  common/src/main/java/apoc/ApocConfig.java
  common/src/main/java/apoc/util/Util.java
Labels: team-cypher-surface, dev

#320 [GfvSwxoH] Fix Docker command docs
  readme.adoc
Labels: team-cypher-surface, docs, dev

#292 [Ci2sJ23z] apoc.trigger.show doesn't work in a system follower
  core/src/main/java/apoc/trigger/TriggerNewProcedures.java
  core/src/test/java/apoc/trigger/TriggerClusterRoutingTest.java
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: dev

#327 [NOID] Fix wrong throttle config in Geocode.SupplierWithKey
  core/src/main/java/apoc/spatial/Geocode.java
Labels: dev

#326 [F61iNGQX] Splits integration tests into their own package
  .github/actions/setup-gradle-cache/action.yaml
  .github/actions/setup-jdk/action.yaml
  .github/actions/setup-snyk/action.yaml
  .github/actions/test-gradle-project/action.yaml
  .github/workflows/CI.yaml
  .github/workflows/snyk.yaml
  build.gradle
  core/build.gradle
  core/src/test/java/apoc/StartupTest.java
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
  core/src/test/java/apoc/export/csv/ImportCsvLdbcTest.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  core/src/test/java/apoc/periodic/PeriodicTest.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
  core/src/test/java/apoc/util/UtilsTest.java
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  it/build.gradle
  it/src/test/java/apoc/it/common/UtilIT.java
  it/src/test/java/apoc/it/core/ApocSplitTest.java
  it/src/test/java/apoc/it/core/CollEnterpriseTest.java
  it/src/test/java/apoc/it/core/ExportCsvIT.java
  it/src/test/java/apoc/it/core/ExportCypherEnterpriseFeaturesTest.java
  it/src/test/java/apoc/it/core/GraphRefactoringEnterpriseTest.java
  it/src/test/java/apoc/it/core/MetaEnterpriseFeaturesTest.java
  it/src/test/java/apoc/it/core/SchemasEnterpriseFeaturesTest.java
  it/src/test/java/apoc/it/core/StartupTest.java
  it/src/test/java/apoc/it/core/TriggerClusterRoutingTest.java
  it/src/test/java/apoc/it/core/TriggerEnterpriseFeaturesTest.java
  it/src/test/java/apoc/it/core/WarmupEnterpriseTest.java
  processor/build.gradle
  settings.gradle
  test-utils/build.gradle
  test-utils/src/main/java/apoc/csv/CsvTestUtil.java
Labels: team-cypher-surface, dev

#334 [F61iNGQX] Removes parallel execution in TeamCity
  .github/actions/test-gradle-project/action.yaml
  gradle.properties
Labels: team-cypher-surface

#331 [bJ4pn0Bj] PeriodicTest.testTerminateCommit is flaky
  core/src/test/java/apoc/periodic/PeriodicTest.java
  test-utils/src/main/java/apoc/periodic/PeriodicTestUtils.java
Labels: dev

#332 [OnEGwZ5A] apoc.hashing.fingerprint can't deal with type byte[]
  core/src/main/java/apoc/hashing/Fingerprinting.java
  core/src/test/java/apoc/hashing/FingerprintingTest.java
Labels: dev

#335 [NOID] Fix error message for apoc.schema.nodes/relationships with include and exclude confs both valuated
  core/src/main/java/apoc/schema/SchemaConfig.java
  core/src/test/java/apoc/schema/SchemasTest.java
  it/src/test/java/apoc/it/core/SchemasEnterpriseFeaturesTest.java
Labels: dev

#336 [NOID] Fixes Snyk CI jobs
  .github/workflows/CI.yaml
  .github/workflows/snyk.yaml
Labels: team-cypher-surface
