Repository neo4j/apoc, pull requests merged in 2023-06, with the labels that each got.

#424 [fdGuLCUX] Add type constraint support
  common/src/main/java/apoc/util/Util.java
  common/src/test/java/apoc/util/UtilTest.java
  core/src/main/java/apoc/schema/Schemas.java
  it/src/test/java/apoc/it/core/SchemasEnterpriseFeaturesTest.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: team-cypher-surface, dev

#426 [NOID] Fixes circular docker dependency in TeamCity
  build.gradle
Labels: bug, cherry-picked

#425 [KUEoGBey] Sanitize text input and add quotes to allow special characters in Atomic procedures
  core/src/main/java/apoc/atomic/Atomic.java
  core/src/test/java/apoc/atomic/AtomicTest.java
Labels: team-cypher-surface, dev

#430 [H5jADF7p] Bump remaining versions to 5.10
  build.gradle
  readme.adoc
Labels: team-cypher-surface, dev

#434 [NOID] Revert docker gradle change
  build.gradle
Labels: team-cypher-surface, dev

#428 [Au0RCa4z] Upgrade dependencies
  build.gradle
  common/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
  test-utils/build.gradle
  test-utils/src/main/java/apoc/util/s3/S3Container.java
Labels: team-cypher-surface, dev

#437 [NOID] Re-enable docker version override
  build.gradle
Labels: team-cypher-surface, dev

#435 [EdwwgWgR] Stream schema results in batches of batchSize
  common/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
  common/src/main/resources/exportAll.cypher
  core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
  core/src/test/java/apoc/export/cypher/ExportCypherMultiRelTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherTestUtils.java
  it/src/test/java/apoc/it/core/ExportCypherS3Test.java
Labels: team-cypher-surface, dev

#436 [VpC8nqNz] Fail build on spotless and licence failures
  .github/actions/test-gradle-project/action.yaml
  LICENSES.txt
  NOTICE.txt
  common/src/main/java/apoc/util/EntityUtil.java
  common/src/main/java/apoc/util/LogsUtil.java
  common/src/main/java/apoc/util/QueryUtil.java
  common/src/test/java/apoc/util/UtilTest.java
  core/src/test/java/apoc/export/ImportAndLoadCoreSecurityTest.java
  core/src/test/java/apoc/export/SecurityTestUtil.java
  core/src/test/java/apoc/load/LoadCoreSecurityTest.java
  core/src/test/java/apoc/load/LoadJsonTest.java
  core/src/test/java/apoc/load/XmlTest.java
  it/src/test/java/apoc/it/core/CypherEnterpriseTest.java
  it/src/test/java/apoc/it/core/ImportJsonEnterpriseFeaturesTest.java
  licenses-3rdparties.gradle
  test-utils/src/main/java/apoc/cypher/CypherTestUtil.java
Labels: team-cypher-surface, dev

#441 [NOID] Uses debian images in the TeamCity CI
  build.gradle
Labels: team-cypher-surface

#439 [NOID] Update testcontainers license dependencies
  LICENSES.txt
  NOTICE.txt
Labels: team-cypher-surface, dev

#446 [NOID] Snyk Hadoop updates
  LICENSES.txt
  NOTICE.txt
  common/build.gradle
  test-utils/build.gradle
Labels: team-cypher-surface, dev

#445 [NOID] Snyk Guava updates
  LICENSES.txt
  NOTICE.txt
  core/build.gradle
Labels: team-cypher-surface, dev
