Repository neo4j/apoc, pull requests merged in 2023-03, with the labels that each got.

#337 [F61iNGQX] Executes integration tests sequentially
  it/build.gradle
Labels: team-cypher-surface

#339 [NOID] Bump version to 5.7.0
  build.gradle
  readme.adoc
Labels: team-cypher-surface, dev

#328 [iTwFvqQ2] apoc.create.clonePathsToVirtual() returns more relationships than it should
  core/src/main/java/apoc/create/Create.java
  core/src/test/java/apoc/create/CreateTest.java
Labels: dev

#353 [nw2aWxrX] Upgrade aws-java-sdk-s3 to 1.12.425 to partially address CVE-2022-42003
  common/build.gradle
  core/src/test/java/apoc/hashing/FingerprintingTest.java
  it/build.gradle
  test-utils/build.gradle
Labels: cherry-picked, dev

#355 [NOID] Remove unused cassandra test dependency
  core/build.gradle
  core/src/test/java/apoc/atomic/AtomicTest.java
  core/src/test/java/apoc/convert/ConvertJsonTest.java
  core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  core/src/test/java/apoc/export/json/ImportJsonTest.java
  core/src/test/java/apoc/graph/GraphsTest.java
  core/src/test/java/apoc/load/LoadJsonTest.java
  core/src/test/java/apoc/load/XmlTest.java
  core/src/test/java/apoc/path/SubgraphTest.java
  core/src/test/java/apoc/periodic/PeriodicTest.java
Labels: team-cypher-surface, dev

#352 [NOID] Making PeriodicTest more lenient
  core/src/test/java/apoc/periodic/PeriodicTest.java
Labels: team-cypher-surface, dev

#357 [NOID] Lenient periodic test
  core/src/test/java/apoc/periodic/PeriodicTest.java
Labels: team-cypher-surface, dev

#359 [tq7tdrWZ] Update Hadoop and JsonPath dependencies
  common/build.gradle
  test-utils/build.gradle
Labels: team-cypher-surface, dev

#356 [1gsD8V8g] Add a more useful error message for export functions
  common/src/main/java/apoc/util/Util.java
  common/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
  core/src/main/java/apoc/export/csv/CsvFormat.java
  core/src/main/java/apoc/export/json/JsonFormat.java
  core/src/test/java/apoc/export/ExportCoreSecurityTest.java
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  core/src/test/java/apoc/export/json/ExportJsonTest.java
  core/src/test/java/apoc/load/LoadCoreSecurityTest.java
  test-utils/src/main/java/apoc/util/TestUtil.java
Labels: team-cypher-surface, dev

#346 [H5vz3qhy] Prevent cascade trigger transactions
  core/src/main/java/apoc/trigger/TriggerHandler.java
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
Labels: dev
