Repository neo4j/apoc, pull requests merged in 2023-08, with the labels that each got.

#463 [Ko3jddbl] Add isDeprecated to apoc.help
  core/src/main/java/apoc/help/Help.java
  core/src/main/java/apoc/help/HelpResult.java
  core/src/test/java/apoc/help/HelpTest.java
Labels: team-cypher-surface, dev

#464 [NOID] Fixes failing path traversal TeamCity tests
  .github/actions/setup-jdk/action.yaml
  core/src/test/java/apoc/export/ExportCoreSecurityTest.java
  core/src/test/java/apoc/export/arrow/ExportArrowSecurityTest.java
Labels: cherry-picked

#470 [NRkjQR1T] Bumps apoc version
  build.gradle
  readme.adoc
Labels: team-cypher-surface

#467 [NOID] Ignore vector indexes when getting indexes from Neo4j.
  common/src/main/java/apoc/export/util/NodesAndRelsSubGraph.java
  common/src/main/java/apoc/util/Util.java
Labels: dev

#466 [NOID] Fix potential ApocConfigTest issues by using a separate conf file for command expansion
  common/src/test/java/apoc/ApocConfigCommandExpansionTest.java
  common/src/test/java/apoc/ApocConfigTest.java
  common/src/test/resources/apoc-config-command-expansion/apoc.conf
Labels: team-cypher-surface, dev

#476 [q5Vf4pi2] Fix broken GeoCode tests
  common/src/test/resources/spatial.json
  core/src/test/java/apoc/spatial/GeocodeTest.java
Labels: team-cypher-surface, dev

#481 [uSvFQccG] Make ExportCypherTest more robust.
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Labels: team-cypher-surface, dev

#483 [NOID] Update Google Cloud Storage dependency
  common/build.gradle
Labels: team-cypher-surface, dev

#484 [YGQfavsP] Dev fix flaky load tests
  core/src/test/java/apoc/load/LoadJsonTest.java
  core/src/test/java/apoc/load/SimpleHttpHandler.java
  core/src/test/java/apoc/load/XmlTest.java
Labels: team-cypher-surface, dev
