Repository neo4j/apoc, pull requests merged in 2024-10, with the labels that each got.

#665 [d4rLFQqM] Align all export modes with quoting consistency
  core/src/main/java/apoc/export/csv/CsvFormat.java
  core/src/main/java/apoc/export/csv/ExportCSV.java
  core/src/main/java/apoc/export/cypher/ExportCypher.java
  core/src/main/java/apoc/export/graphml/ExportGraphML.java
  core/src/main/java/apoc/export/json/ExportJson.java
  core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
  core/src/test/resources/procedures.json
Labels: team-cypher-surface, dev

#668 [NOID] Bump to 5.26
  build.gradle
  readme.adoc
Labels: team-cypher-surface, dev

#667 [v8imq7eo] Fix coll array handling
  common/src/main/java/apoc/util/Util.java
  core/src/main/java/apoc/coll/Coll.java
  core/src/test/java/apoc/coll/CollTest.java
  core/src/test/resources/functions.json
Labels: team-cypher-surface, dev

#666 [yVM4sJbH] Dev fix round trip for csv loading
  common/src/main/java/apoc/load/Mapping.java
  common/src/main/java/apoc/meta/Types.java
  core/src/test/java/apoc/export/csv/ImportCsvTest.java
Labels: team-cypher-surface, dev

#669 [lYfZxdRz] Deprecate and remove procedures/functions for Cypher 25
  core/src/main/java/apoc/convert/Json.java
  core/src/main/java/apoc/create/Create.java
  core/src/main/java/apoc/export/arrow/ExportArrow.java
  core/src/main/java/apoc/load/LoadArrow.java
  core/src/main/java/apoc/load/LoadJson.java
  core/src/main/java/apoc/log/Neo4jLogStream.java
  core/src/main/java/apoc/map/Maps.java
  core/src/main/java/apoc/text/Strings.java
  core/src/main/java/apoc/trigger/Trigger.java
  core/src/main/java/apoc/warmup/Warmup.java
  core/src/test/resources/functions.json
  core/src/test/resources/procedures.json
  it/src/test/java/apoc/it/core/ApocVersionsTest.java
Labels: team-cypher-surface, dev

#671 [NOID] Update testContainers
  LICENSES.txt
  NOTICE.txt
  build.gradle
Labels: team-cypher-surface, dev

#672 [aWY2zoX5] Replaced testTerminatePeriodicQuery with testTerminateWithCommand
  core/src/test/java/apoc/periodic/PeriodicTest.java
  test-utils/src/main/java/apoc/periodic/PeriodicTestUtils.java
Labels: team-cypher-surface

#677 [rzjiVl4e] Add new Core API constraints
  common/src/main/java/apoc/util/Util.java
  common/src/test/java/apoc/util/UtilTest.java
Labels: team-cypher-surface, dev

#674 [bkym7TcZ] Optimise apoc.refactor.cloneSubgraph
  common/build.gradle
  core/build.gradle
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/test/java/apoc/refactor/CloneSubgraphTest.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
  core/src/test/resources/procedures.json
  processor/build.gradle
Labels: dev

#678 [Carz4Ljs] Safe use of transactions in export csv
  common/src/main/java/apoc/export/util/ExportUtils.java
  common/src/main/java/apoc/export/util/NodesAndRelsSubGraph.java
  common/src/main/java/org/neo4j/cypher/export/ExportData.java
  core/src/main/java/apoc/export/csv/CsvFormat.java
  core/src/main/java/apoc/export/csv/ExportCSV.java
  core/src/main/java/apoc/export/graphml/ExportGraphML.java
  core/src/main/java/apoc/export/json/ExportJson.java
Labels: bug, dev

#681 [NOID] Kernel debug flag
  build.gradle
  core/src/main/java/apoc/warmup/Warmup.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: dev
