Repository neo4j/apoc, pull requests merged in 2024-11, with the labels that each got.

#675 [3Hl7fTsQ] Dev fix misleading name column
  core/src/main/java/apoc/help/Help.java
  core/src/main/java/apoc/schema/Schemas.java
  core/src/test/java/apoc/schema/SchemasTest.java
  it/src/test/java/apoc/it/core/StartupTest.java
  processor/src/main/java/apoc/processor/ApocProcessor.java
  processor/src/main/java/apoc/processor/ExtensionClassWriter.java
  processor/src/main/java/apoc/processor/SignatureVisitor.java
  processor/src/test/java/apoc/processor/ApocProcessorTest.java
  processor/src/test/java/apoc/processor/ProcedureSignatureVisitorTest.java
  processor/src/test/java/apoc/processor/UserAggregationFunctionSignatureVisitorTest.java
  processor/src/test/java/apoc/processor/UserFunctionSignatureVisitorTest.java
Labels: team-cypher-surface, dev

#686 [9aSkAHkN] add missing license headers
  common/src/main/java/apoc/result/CypherStatementMapResult.java
  common/src/main/java/apoc/result/DataProgressInfo.java
  core/src/main/java/apoc/export/csv/CustomCSVWriter.java
  it/src/test/java/apoc/it/core/PeriodicIterateTest.java
Labels: team-cypher-surface, dev

#687 Add new trello action
  .github/workflows/traceability-comments-trigger.yaml
  .github/workflows/traceability-comments.yaml
Labels: team-cypher-surface, dev

#688 APOC to jdk 21
  .github/actions/setup-jdk/action.yaml
  build.gradle
  common/build.gradle
  core/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  processor/src/main/java/apoc/processor/ApocProcessor.java
  readme.adoc
Labels: team-cypher-surface, dev

#691 Update apoc help so that it does not rely on extended at all
  .github/workflows/traceability-comments.yaml
  core/src/main/java/apoc/help/Help.java
  core/src/main/java/apoc/help/HelpUtil.java
  it/src/test/java/apoc/it/core/StartupTest.java
Labels: team-cypher-surface, dev, No Trello

#694 Update description of apoc.load.jsonParams
  core/src/main/java/apoc/load/LoadJson.java
  core/src/test/resources/procedures.json
Labels: No Trello
