Repository neo4j/apoc, pull requests merged in 2024-04, with the labels that each got.

#613 [z9rBzmVK] Make recursiveRebind nullsafe for maps.
  common/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/periodic/PeriodicTest.java
Labels: bug, team-cypher-surface, dev

#610 [olbYUBeG] Added meta-data to batches in periodic iterate
  core/src/main/java/apoc/periodic/Periodic.java
  it/src/test/java/apoc/it/core/PeriodicIterateTest.java
  test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java
Labels: bug, team-cypher-surface

#614 [VSncHHoB] Bump versions to 5.20
  LICENSES.txt
  NOTICE.txt
  build.gradle
  readme.adoc
Labels: team-cypher-surface, dev

#618 [pb3CtuNX] Adds convert.paths.toTree to deprecate old convert.toTree
  .github/workflows/CI.yaml
  LICENSES.txt
  NOTICE.txt
  core/src/main/java/apoc/convert/Json.java
  core/src/main/java/apoc/periodic/Periodic.java
  core/src/test/java/apoc/convert/PathsToJsonTreeTest.java
  it/src/test/java/apoc/it/core/ApocSplitTest.java
  it/src/test/java/apoc/it/core/PeriodicIterateTest.java
  test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java
Labels: cherry-picked
