Repository neo4j/apoc, pull requests merged in 2024-12, with the labels that each got.

#697 Error on typos for uniqueness
  core/src/main/java/apoc/path/PathExplorer.java
  core/src/test/java/apoc/path/ExpandPathTest.java
Labels: team-cypher-surface, dev

#698 Add float type and fix values not showing with useTypes is used
  common/src/main/java/apoc/export/util/MetaInformation.java
  core/src/main/java/apoc/export/csv/CsvFormat.java
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
Labels: team-cypher-surface, dev

#700 Update to behave differently for APOC extended
  common/src/main/java/apoc/ApocExtensionFactory.java
Labels: team-cypher-surface, dev

#702 Update to behave differently for APOC extended (#700)
  common/src/main/java/apoc/ApocExtensionFactory.java
Labels: team-cypher-surface, cherry-picked, dev, No Trello

#704 Deprecate apoc.refactor.deleteAndReconnect
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/test/resources/procedures.json
Labels: dev

#705 Test signatures with Cypher versions
  core/src/test/java/apoc/ArgumentDescriptionsTest.java
  core/src/test/resources/functions.json
  core/src/test/resources/functions/common/functions.json
  core/src/test/resources/functions/cypher25/functions.json
  core/src/test/resources/functions/cypher5/functions.json
  core/src/test/resources/procedures/common/procedures.json
  core/src/test/resources/procedures/cypher25/procedures.json
  core/src/test/resources/procedures/cypher5/procedures.json
Labels: dev, No Trello

#707 Version bump: 2025.01.0
  LICENSES.txt
  NOTICE.txt
  build.gradle
  core/src/main/java/apoc/help/HelpUtil.java
  core/src/main/java/apoc/schema/Schemas.java
  readme.adoc
Labels: dev, No Trello

#709 Fix config maps for graphml procs
  core/src/main/java/apoc/export/graphml/ExportGraphML.java
  core/src/test/resources/procedures/common/procedures.json
Labels: team-cypher-surface, dev, No Trello
