Repository neo4j/apoc, pull requests merged in 2024-01, with the labels that each got.

#562 [PWX3u4Bn] Version bump
  build.gradle
  readme.adoc
Labels: team-cypher-surface, dev

#561 [yaWCMgIP] Exclude asm to fix startup issue
  LICENSES.txt
  NOTICE.txt
  common/build.gradle
Labels: team-cypher-surface, dev

#565 [yaWCMgIP] Exclude asm to fix startup issue (#561)
  LICENSES.txt
  NOTICE.txt
  common/build.gradle
Labels: cherry-picked

#566 [yaWCMgIP] Exclude asm to fix startup issue (#561)
  LICENSES.txt
  NOTICE.txt
  common/build.gradle
Labels: cherry-picked

#567 [NOID] Update neo4j docker override params
  build.gradle
Labels: cherry-picked

#569 [NOID] Use count methods with transaction state
  core/src/main/java/apoc/meta/Meta.java
Labels: dev

#572 [SGrPWNEf] Fixes backslashes parsing in csv import / export
  core/src/main/java/apoc/export/csv/CsvEntityLoader.java
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
Labels: cherry-picked, dev

#571 [mMXNEtoY] Add default value for optionalData.
  common/src/main/java/apoc/load/Mapping.java
Labels: bug, dev

#579 [NOID] Upgrade driver used in tests to 5.16.0
  LICENSES.txt
  NOTICE.txt
  it/src/test/java/apoc/it/core/CypherEnterpriseTest.java
  it/src/test/java/apoc/it/core/ExportCsvIT.java
  it/src/test/java/apoc/it/core/GraphRefactoringEnterpriseTest.java
  it/src/test/java/apoc/it/core/TriggerEnterpriseFeaturesTest.java
  test-utils/build.gradle
  test-utils/src/main/java/apoc/cypher/CypherTestUtil.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: team-cypher-surface

#575 [NOID] Updates libraries suggested by Snyk
  LICENSES.txt
  NOTICE.txt
  common/build.gradle
  it/build.gradle
  test-utils/build.gradle
Labels: team-cypher-surface

#574 [NOID] Fixes directory that should be non existing
  core/src/test/java/apoc/export/ExportCoreSecurityTest.java
Labels: team-cypher-surface
