Repository neo4j/apoc, pull requests merged in 2025-09, with the labels that each got.

#848 Update generated constraint name
  core/src/test/java/apoc/schema/SchemasTest.java
Labels: dev, No Trello

#844 Fix flaky tests for vectors
  core/src/test/java/apoc/meta/MetaTest.java
  core/src/test/java/apoc/util/UtilsTest.java
Labels: team-cypher-surface, dev

#851 Bump netty
  build.gradle
  it/src/test/java/apoc/it/core/ApocSplitTest.java
  it/src/test/java/apoc/it/core/RBACOnLoadTest.java
  it/src/test/java/apoc/it/core/StartupTest.java
Labels: team-cypher-surface, No Trello, 5.26
