Repository neo4j/apoc, pull requests merged in 2025-08, with the labels that each got.

#815 Migrate some tests to junit 5
  core/src/test/java/apoc/agg/CollAggregationTest.java
  core/src/test/java/apoc/agg/GraphAggregationTest.java
  core/src/test/java/apoc/agg/MaxAndMinItemsAggregationTest.java
  core/src/test/java/apoc/agg/MedianTest.java
  core/src/test/java/apoc/agg/PercentilesTest.java
  core/src/test/java/apoc/agg/ProductAggregationTest.java
  core/src/test/java/apoc/agg/StatisticsTest.java
  core/src/test/java/apoc/algo/CoverTest.java
  core/src/test/java/apoc/algo/PathFindingTest.java
  core/src/test/java/apoc/atomic/AtomicTest.java
  core/src/test/java/apoc/bitwise/BitwiseOperationsTest.java
  core/src/test/java/apoc/coll/CollTest.java
  core/src/test/java/apoc/convert/ConvertJsonTest.java
  core/src/test/java/apoc/convert/ConvertTest.java
  core/src/test/java/apoc/convert/PathsToJsonTreeTest.java
  core/src/test/java/apoc/create/CreateTest.java
  core/src/test/java/apoc/cypher/CypherIsVersionDifferentTest.java
  core/src/test/java/apoc/cypher/CypherTest.java
Labels: No Trello

#816 Update hadoop
  LICENSES.txt
  NOTICE.txt
  common/build.gradle
  test-utils/build.gradle
Labels: team-cypher-surface, dev, No Trello

#818 Update google cloud storage
  common/build.gradle
Labels: team-cypher-surface, dev, No Trello

#820 Add option to continue on error: apoc.periodic.repeat
  common/src/main/java/apoc/periodic/PeriodicUtils.java
  core/src/main/java/apoc/periodic/Periodic.java
  core/src/test/java/apoc/periodic/PeriodicTest.java
  core/src/test/resources/procedures/common/procedures.json
  core/src/test/resources/procedures/cypher25/procedures.json
  core/src/test/resources/procedures/cypher5/procedures.json
Labels: team-cypher-surface, dev, No Trello

#826 Update Google cloud storage (#821)
  LICENSES.txt
  NOTICE.txt
  build.gradle
  common/build.gradle
  test-utils/build.gradle
Labels: team-cypher-surface, cherry-picked, 5.26
