Repository neo4j/apoc, pull requests merged in 2025-02, with the labels that each got.

#725 Add ability to test different cypher versions globally
  common/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/ArgumentDescriptionsTest.java
  core/src/test/java/apoc/convert/ConvertJsonTest.java
  core/src/test/java/apoc/convert/PathsToJsonTreeTest.java
  core/src/test/java/apoc/cypher/CypherTest.java
  core/src/test/java/apoc/export/ImportAndLoadCoreSecurityTest.java
  core/src/test/java/apoc/export/SecurityTestUtil.java
  core/src/test/java/apoc/export/arrow/ArrowTest.java
  core/src/test/java/apoc/export/arrow/ExportArrowSecurityTest.java
  core/src/test/java/apoc/help/HelpTest.java
  core/src/test/java/apoc/load/LoadJsonTest.java
  core/src/test/java/apoc/map/MapsTest.java
  core/src/test/java/apoc/meta/MetaTest.java
  core/src/test/java/apoc/schema/SchemasTest.java
  core/src/test/java/apoc/text/StringsTest.java
  core/src/test/java/apoc/trigger/TriggerDisabledTest.java
  core/src/test/java/apoc/trigger/TriggerTest.java
  core/src/test/java/apoc/warmup/WarmupTest.java
  it/src/test/java/apoc/it/core/ApocVersionsTest.java
  test-utils/src/main/java/org/neo4j/test/rule/DbmsRule.java
Labels: team-cypher-surface, dev

#730 Update CodeQL
  .github/workflows/CI.yaml
Labels: team-cypher-surface, dev, No Trello

#727 Dev test cypher versions docker
  common/src/main/java/apoc/util/Util.java
  it/src/test/java/apoc/it/core/ApocSplitTest.java
  it/src/test/java/apoc/it/core/RBACOnLoadTest.java
  it/src/test/java/apoc/it/core/SchemasEnterpriseFeaturesTest.java
  it/src/test/java/apoc/it/core/TriggerClusterRoutingTest.java
  it/src/test/java/apoc/it/core/TriggerEnterpriseFeaturesTest.java
  it/src/test/java/apoc/it/core/WarmupEnterpriseTest.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: team-cypher-surface, dev

#710 Add other types to give a more robust grouping proc
  core/src/main/java/apoc/nodes/Grouping.java
  core/src/test/java/apoc/nodes/GroupingTest.java
Labels: team-cypher-surface, dev, No Trello

#733 Add close() method to `LimitedSizeInputStream`
  common/src/main/java/apoc/export/util/LimitedSizeInputStream.java
Labels: No Trello

#734 add close method to LimitedSizeInputStream
  common/src/main/java/apoc/export/util/LimitedSizeInputStream.java
Labels: cherry-picked, No Trello

#726 Adapt to new preparser API
  common/src/main/java/apoc/util/LogsUtil.java
  common/src/main/java/apoc/util/Util.java
  core/src/main/java/apoc/cypher/CypherInitializer.java
  core/src/test/java/apoc/export/arrow/ArrowTest.java
  core/src/test/java/apoc/export/arrow/ExportArrowSecurityTest.java
  core/src/test/java/apoc/trigger/TriggerDisabledTest.java
  core/src/test/java/apoc/trigger/TriggerTest.java
  core/src/test/java/apoc/util/LogsUtilTest.java
  core/src/test/java/apoc/warmup/WarmupTest.java
  it/src/test/java/apoc/it/core/WarmupEnterpriseTest.java
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
  test-utils/src/main/java/org/neo4j/test/rule/DbmsRule.java
Labels: No Trello

#732 testTerminateCommit: stop test going out of memory
  core/src/test/java/apoc/periodic/PeriodicTest.java
Labels: team-cypher-surface, No Trello, 5.26

#735 testTerminateCommit: stop test going out of memory (#732)
  core/src/test/java/apoc/periodic/PeriodicTest.java
Labels: cherry-picked, dev, No Trello

#738 Fix setting
  test-utils/src/main/java/apoc/util/TestContainerUtil.java
Labels: No Trello

#741 Bump transitive dependency
  common/build.gradle
Labels: No Trello

#728 Dev make apoc version aware
  LICENSES.txt
  NOTICE.txt
  common/src/main/java/apoc/cypher/CypherUtils.java
  common/src/main/java/apoc/util/Util.java
  core/src/main/java/apoc/atomic/Atomic.java
  core/src/main/java/apoc/coll/Coll.java
  core/src/main/java/apoc/cypher/Cypher.java
  core/src/main/java/apoc/cypher/CypherFunctions.java
  core/src/main/java/apoc/cypher/Timeboxed.java
  core/src/main/java/apoc/example/Examples.java
  core/src/main/java/apoc/export/csv/ExportCSV.java
  core/src/main/java/apoc/export/cypher/ExportCypher.java
  core/src/main/java/apoc/export/graphml/ExportGraphML.java
  core/src/main/java/apoc/export/json/ExportJson.java
  core/src/main/java/apoc/graph/Graphs.java
  core/src/main/java/apoc/help/Help.java
  core/src/main/java/apoc/merge/Merge.java
  core/src/main/java/apoc/meta/Meta.java
  core/src/main/java/apoc/nodes/Nodes.java
  core/src/main/java/apoc/periodic/Periodic.java
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/main/java/apoc/refactor/rename/Rename.java
  core/src/main/java/apoc/schema/Schemas.java
  core/src/main/java/apoc/search/ParallelNodeSearch.java
  core/src/main/java/apoc/trigger/Trigger.java
  core/src/main/java/apoc/trigger/TriggerNewProcedures.java
  core/src/test/java/apoc/HelperProcedures.java
  core/src/test/java/apoc/cypher/CypherTest.java
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherTestUtils.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTestUtil.java
  core/src/test/java/apoc/export/json/ExportJsonTest.java
  core/src/test/java/apoc/graph/GraphsTest.java
  core/src/test/java/apoc/meta/MetaTest.java
  core/src/test/java/apoc/periodic/PeriodicTest.java
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
  core/src/test/java/apoc/trigger/TriggerTest.java
  test-utils/src/main/java/apoc/trigger/TriggerTestUtil.java
Labels: team-cypher-surface, dev

#742 Fix compilation error in DbmsRule
  test-utils/src/main/java/org/neo4j/test/rule/DbmsRule.java
Labels: team-cypher-surface, dev, No Trello

#743 Fix virtual node id working
  common/src/main/java/apoc/result/VirtualNode.java
  core/src/test/java/apoc/create/CreateTest.java
Labels: team-cypher-surface, dev

#744 Fix apoc.meta.subgraph for non-existing labels and types
  common/src/main/java/org/neo4j/cypher/export/DatabaseSubGraph.java
  core/src/test/java/apoc/meta/MetaTest.java
Labels: team-cypher-surface, dev
