Repository neo4j/apoc, pull requests merged in 2025-10, with the labels that each got.

#852 Update schema descriptor for disjunction of entity tokens for fulltext
  core/src/test/java/apoc/schema/SchemasTest.java
Labels: dev, No Trello

#853 Fix publications
  build.gradle
  common/build.gradle
  core/build.gradle
  greclipse.properties
  it/build.gradle
  licenses-3rdparties.gradle
  licenses-source-header.gradle
  processor/build.gradle
  teamcity-repository.gradle
  test-utils/build.gradle
Labels: No Trello

#843 Temporal Parse deprecations
  core/src/main/java/apoc/date/Date.java
  core/src/main/java/apoc/temporal/TemporalProcedures.java
  core/src/test/resources/functions/common/functions.json
  core/src/test/resources/functions/cypher25/functions.json
  core/src/test/resources/functions/cypher5/functions.json
Labels: team-cypher-surface, dev, No Trello

#854 Updated manifest with more information
  core/build.gradle
  processor/build.gradle
Labels: team-cypher-surface, dev, No Trello
