Repository neo4j/apoc, pull requests merged in 2025-01, with the labels that each got.

#714 Update the way we fetch the Neo version
  .github/workflows/CI.yaml
  .github/workflows/traceability-comments.yaml
Labels: team-cypher-surface, No Trello

#716 5.26 fix builds
  .github/workflows/CI.yaml
  .github/workflows/traceability-comments.yaml
Labels: No Trello, 5.26

#712 Add option to wrap a nodes id to the apoc.create.virtual.fromNode
  common/src/main/java/apoc/result/VirtualNode.java
  core/src/main/java/apoc/create/Create.java
  core/src/test/java/apoc/create/CreateTest.java
  core/src/test/resources/functions/common/functions.json
Labels: team-cypher-surface, dev, No Trello

#718 Missed a line with the new aws fetching
  .github/workflows/CI.yaml
Labels: No Trello

#717 5.26 LTS clone subgraph properties fix
  common/src/main/java/apoc/ApocExtensionFactory.java
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/test/java/apoc/refactor/CloneSubgraphTest.java
Labels: No Trello, 5.26

#715 Fixed issue with properties in CloneSubgraph
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/test/java/apoc/refactor/CloneSubgraphTest.java
Labels: team-cypher-surface, dev, No Trello

#703 Fix handling of constraints in refactor procedures
  core/src/main/java/apoc/refactor/GraphRefactoring.java
  core/src/test/java/apoc/ArgumentDescriptionsTest.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
  core/src/test/resources/procedures/common/procedures.json
Labels: dev

#711 Add failOnError and return status options to apoc.cypher.timeboxed
  core/src/main/java/apoc/cypher/Timeboxed.java
  core/src/test/java/apoc/cypher/CypherTest.java
  core/src/test/resources/procedures/common/procedures.json
  core/src/test/resources/procedures/cypher25/procedures.json
  core/src/test/resources/procedures/cypher5/procedures.json
Labels: team-cypher-surface, dev, No Trello

#723 Remove resolvers on db shutdown
  common/src/main/java/apoc/ApocExtensionFactory.java
  common/src/main/java/apoc/RegisterComponentFactory.java
Labels: team-cypher-surface, dev, No Trello

#724 Remove resolvers on db shutdown
  common/src/main/java/apoc/ApocExtensionFactory.java
  common/src/main/java/apoc/RegisterComponentFactory.java
Labels: team-cypher-surface, cherry-picked, No Trello, 5.26
