Repository neo4j/apoc, pull requests merged in 2025-03, with the labels that each got.

#748 Bump dependency
  common/build.gradle
Labels: No Trello

#749 Bump dependency
  common/build.gradle
Labels: No Trello

#747 Deprecated hyperbolic functions moved into Cypher
  core/src/main/java/apoc/math/Maths.java
  core/src/test/resources/functions/common/functions.json
  core/src/test/resources/functions/cypher25/functions.json
  core/src/test/resources/functions/cypher5/functions.json
Labels: team-cypher-surface, dev, No Trello

#746 Set up more robust virtual entities for deleted nodes and relationships
  common/src/main/java/apoc/result/VirtualNode.java
  common/src/main/java/apoc/result/VirtualRelationship.java
  common/src/test/java/apoc/result/VirtualNodeTest.java
  core/src/main/java/apoc/trigger/TriggerMetadata.java
  core/src/test/java/apoc/graph/GraphsTest.java
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
Labels: team-cypher-surface, dev, No Trello

#751 Fix long-running test assertions
  core/src/test/java/apoc/periodic/PeriodicTest.java
  test-utils/src/main/java/apoc/periodic/PeriodicTestUtils.java
  test-utils/src/main/java/apoc/util/TransactionTestUtil.java
Labels: No Trello

#753 Filter out vector types as they aren't currently storable
  core/src/test/java/apoc/util/UtilsTest.java
Labels: team-cypher-surface, dev, No Trello

#754 Fix broken build
  build.gradle
Labels: No Trello

#752 Bump dependencies
  build.gradle
  common/build.gradle
  core/build.gradle
  core/src/test/java/apoc/agg/CollAggregationTest.java
  core/src/test/java/apoc/convert/ConvertJsonTest.java
  core/src/test/java/apoc/convert/PathsToJsonTreeTest.java
  core/src/test/java/apoc/export/arrow/ArrowTest.java
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherMultiRelTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
  core/src/test/java/apoc/export/json/ExportJsonTest.java
  core/src/test/java/apoc/nodes/NodesTest.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
  core/src/test/java/apoc/schema/SchemasTest.java
  core/src/test/java/apoc/warmup/WarmupTest.java
  gradle/wrapper/gradle-wrapper.properties
  processor/build.gradle
  test-utils/build.gradle
Labels: No Trello

#756 Fix trigger related ids for relationships and nodes
  common/src/main/java/apoc/result/VirtualNode.java
  common/src/main/java/apoc/result/VirtualRelationship.java
  common/src/test/java/apoc/result/VirtualNodeTest.java
  core/src/main/java/apoc/trigger/TriggerMetadata.java
  core/src/test/java/apoc/graph/GraphsTest.java
  core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
Labels: team-cypher-surface, cherry-picked, No Trello, 5.26

#760 Fix issue with import cast exception
  core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
Labels: team-cypher-surface, dev, No Trello

#762 Fix issue with empty arrays not being merged
  core/src/main/java/apoc/refactor/util/PropertiesManager.java
  core/src/test/java/apoc/refactor/GraphRefactoringTest.java
Labels: team-cypher-surface, dev, No Trello

#763 Add testing of Cypher export
  core/src/test/java/apoc/export/RandomGraphExportTest.java
  core/src/test/java/apoc/test/util/RandomGraph.java
Labels: No Trello

#764 Update test folder to match Neo's new naming
  common/src/main/java/apoc/ApocConfig.java
Labels: team-cypher-surface, dev, No Trello

#765 Fix flaky test
  common/src/main/java/apoc/export/cypher/formatter/CypherFormatterUtils.java
  core/src/test/java/apoc/test/util/RandomGraph.java
Labels: No Trello
