Repository neo4j/apoc, pull requests merged in 2025-05, with the labels that each got.

#774 Fix unsafe use of transactions in Cypher export
  common/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
  core/src/main/java/apoc/export/cypher/ExportCypher.java
  core/src/test/java/apoc/export/cypher/ExportCypherMultiRelTest.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Labels: No Trello

#776 Make periodic procedures safe to call concurrently
  common/src/main/java/apoc/periodic/PeriodicUtils.java
  common/src/main/java/apoc/util/Util.java
  core/src/main/java/apoc/periodic/Periodic.java
  core/src/test/java/apoc/periodic/PeriodicTest.java
  test-utils/src/main/java/apoc/periodic/PeriodicTestUtils.java
Labels: No Trello

#777 Migrate test to Junit 5
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
Labels: No Trello

#785 Fix to work with CalVer versions
  build.gradle
  versions.json
Labels: team-cypher-surface

#786 Mute write operations not allowed errors on db drop
  core/src/main/java/apoc/cypher/CypherInitializer.java
Labels: dev, No Trello

#789 Fix flaky tests
  core/src/test/java/apoc/periodic/PeriodicTest.java
Labels: dev, No Trello

#790 Add POINT value inference
  common/src/main/java/apoc/util/Util.java
  core/src/test/java/apoc/export/json/ImportJsonTest.java
  core/src/test/resources/exportJSON/importPointValues.json
  core/src/test/resources/exportJSON/invalidPointValues.json
Labels: team-cypher-surface, dev, No Trello
