Repository neo4j/apoc, pull requests merged in 2025-07, with the labels that each got.

#797 Add some vector support to APOC
  common/src/main/java/apoc/meta/Types.java
  common/src/main/java/apoc/meta/tablesforlabels/PropertyTracker.java
  core/src/test/java/apoc/export/arrow/ArrowTest.java
  core/src/test/java/apoc/export/arrow/ExportArrowSecurityTest.java
  core/src/test/java/apoc/export/csv/ExportCsvTest.java
  core/src/test/java/apoc/meta/MetaTest.java
  core/src/test/java/apoc/refactor/CloneSubgraphTest.java
  it/src/test/java/apoc/it/core/ApocVersionsTest.java
Labels: team-cypher-surface, dev, No Trello

#798 Add NAN support to graphml imports
  core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java
  core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
Labels: team-cypher-surface, dev, No Trello

#802 fix broken references
  core/src/test/java/apoc/test/util/RandomGraph.java
Labels: No Trello

#800 Bump netty version
  LICENSES.txt
  NOTICE.txt
  build.gradle
Labels: No Trello

#803 Fix compatibility check in StartupTest
  it/src/test/java/apoc/it/core/StartupTest.java
Labels: team-cypher-surface, dev, No Trello

#805 Migrate from deprecated neo4j-java-driver methods to new ones
  it/src/test/java/apoc/it/core/ExportCypherEnterpriseFeaturesTest.java
  it/src/test/java/apoc/it/core/ImportJsonEnterpriseFeaturesTest.java
  it/src/test/java/apoc/it/core/MetaEnterpriseFeaturesTest.java
  it/src/test/java/apoc/it/core/SchemasEnterpriseFeaturesTest.java
  test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java
Labels: dev, No Trello

#810 Dependency constraint
  LICENSES.txt
  NOTICE.txt
  common/build.gradle
Labels: No Trello

#812 spotless
  it/src/test/java/apoc/it/core/ExportCypherEnterpriseFeaturesTest.java
  it/src/test/java/apoc/it/core/ImportJsonEnterpriseFeaturesTest.java
  it/src/test/java/apoc/it/core/MetaEnterpriseFeaturesTest.java
  it/src/test/java/apoc/it/core/SchemasEnterpriseFeaturesTest.java
Labels: team-cypher-surface, No Trello, 5.26

#814 Fix compilation
  core/src/test/java/apoc/ArgumentDescriptionsTest.java
Labels: No Trello
