Repository neo4j/apoc, pull requests merged in 2025-04, with the labels that each got.

#750 Fix virtual entities hashCode
  common/src/main/java/apoc/result/VirtualNode.java
  common/src/main/java/apoc/result/VirtualRelationship.java
Labels: No Trello

#766 Allow null values for apoc.util.validatePredicate
  core/src/main/java/apoc/util/Utils.java
  core/src/test/java/apoc/util/UtilsTest.java
Labels: team-cypher-surface, dev, No Trello

#767 Fix long-running test assertions
  build.gradle
  core/src/test/java/apoc/periodic/PeriodicTest.java
  readme.adoc
  test-utils/src/main/java/apoc/periodic/PeriodicTestUtils.java
  test-utils/src/main/java/apoc/util/TransactionTestUtil.java
Labels: team-cypher-surface, cherry-picked, No Trello, 5.26

#772 Fix issue with export with constraints
  common/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Labels: team-cypher-surface, dev, No Trello

#773 Close resources
  LICENSES.txt
  NOTICE.txt
  common/src/main/java/apoc/export/util/NodesAndRelsSubGraph.java
  common/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
  common/src/main/java/org/neo4j/cypher/export/DatabaseSubGraph.java
  common/src/main/java/org/neo4j/cypher/export/SubGraph.java
  core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
  core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Labels: No Trello
